import requests

## Constants
url = "https://portal.your.md/v4/logout"
token = "eyJraWQiOiI0Y2RmY2Q0OS1kM2QyLTRlZGMtYThlZi02MDY5ZjRmZWYwNmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ5bWRNb3JzZV9UNGlzODBaYkZhODFORmZQSnhRUmowMWNRSkJhZ25vaE5qdGxJS0VRNDh2cyIsImF1ZCI6Ikhlcm9lc1RlY2hub2xvZ3kiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImRldmljZV9pZCI6InBhcnRuZXJfSGVyb2VzVGVjaG5vbG9neV8wNDZmNWRhZGE1NTllYzI0MGE3NWI4ZTA5ZDJmMTkwYjY0MGUzYWVjMjJiMTA4OGQxYmNkNGZmMjU1NTE1YjljIiwibmFtZSI6IkFiaHl1ZGF5IiwiZGVsZXRlX2F0IjoxNzEwMTA1ODAzLCJwaWQiOiJQekhndFdEc2k2ZTY4Ukh4dzBscGNHOHk4dlIwWFpYUSIsImVtYWlsIjoiYWJoeXVkYXlsdXRocmEyMDAwQGdtYWlsLmNvbSIsImlzcyI6InltZC1pbnRlcm5hbC1zZXJ2aWNlLXByb2QiLCJqdGkiOiJkOGU3MDM0MC00NzA2LTRhMTEtOGZjOC0xZWI5NDc1N2FkMTEiLCJpYXQiOjE3MDk5MzMwMDMsImV4cCI6MTcwOTkzNDgwM30.Rg835zisr3_DnC8uq9q4X7TE5_2qOx3dgLmSTZzIvCFzLE8_xuKmKhvPXMtUT-vOSdKbCApIFycls0prVIdDK6UyBaXKezWcQ_0FLeoEMHgRlxxnqV_0qDNFzNzQ7T_wPJd3i-b7hC6wLJ95a225hIFiehtlM1WTiIJVHctkiptPybkT2o__zeSt4UjuxxUf914_pOmheZUweZNHViIJYsnRFfQPn4XIa5RSXI-xy-ziR_yTDM9lh-L7WBNIgiUSlTbT66MNbUIZ1OI9UCfq-X4abTG7EI_qcU4QlcMBevwxgCHkujtVLSy9cTSQpydqCc3mH9OLJhszWSWM0Nhc8g"

def logout():
    headers = {
        "accept": "*/*",
        "authorization": "Bearer " + token
    }

    response = requests.post(url, headers=headers)

    print(response.text)
    return(response.json)

logout()